[project]
name = "experiment"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "trl-env",
    "mini-racer",
    "pydantic",
    "sympy",
    "peft",
    "python-dotenv",
    "tensorboard",
    "jiwer",
    "bitsandbytes",
    "mlx-lm ; sys_platform == 'darwin'",
]

[tool.uv.sources]
trl-env = { workspace = true }
