from __future__ import annotations
from typing import Protocol

class RolloutModel(Protocol):
    def __enter__(self) -> RolloutModelWithCache: ...
    def __exit__(self, exc_type, exc, tb): ...

class RolloutModelWithCache(Protocol):
    def generate(self, input_ids: list[int]) -> tuple[list[int], list[float]]: ...
